[tool.poetry]
name = "ikastool"
version = "0.1.0"
authors = []
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
flask = "^3.0.0"
disnake = "2.8.1"
sqlitedict = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
